### ISSUE TITLE
兄弟，captchaToken方法你到底是怎么知道pikpak怎么计算的

### ISSUE THREAD

**Issue by magicalapp** [lyqingye/pikpak-go#7]
兄弟，captchaToken方法你到底是怎么知道pikpak怎么计算的

**Comment by magicalapp** [comment]
看到注释了，谢谢

**Comment by 9292922** [comment]
但是我还是不知道在哪里可以找到包含calculateCaptchaSign的js文件，可以告诉一下触发时机吗

**Comment by magicalapp** [comment]
我看了那个js乱七八糟啊，很难还原

**Comment by magicalapp** [comment]
实在看不懂是怎么计算的，不知道这样写sign计算对不对
![image](https://github.com/lyqingye/pikpak-go/assets/25112746/3ff3daff-d41b-4aa8-97aa-0e6028496a3f)

**Comment by lq1984** [comment]
注释里面有写，剩下的自己下断点调试吧。
